web_profiler:
    toolbar: true
    intercept_redirects: false

framework:
    profiler: { only_exceptions: false }
    session:
        handler_id: session.handler.native_file
        save_path: "%kernel.root_dir%/sessions"